name: Build Application
on:
  push:
    branches:
      - main
    paths:
      - src/**
      - pyproject.toml
      - .github/workflows/*
jobs:
  bump:
    runs-on: ubuntu-latest
    outputs:
      commit: ${{ steps.commit.outputs.commit_long_sha }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Extract current version
        run: echo "VERSION=$(sed -nr 's/version = "(.+)"/\1/p' pyproject.toml)" >> $GITHUB_ENV

      - name: Compute new version
        run: echo "NEW_VERSION=$(echo ${{ env.VERSION }} | awk -F. '/[0-9]+\./{$NF++;print}' OFS=.)" >> $GITHUB_ENV
        
      - name: Bump version in pyproject.toml
        run: sed -ri "s/version = \".+\"/version = \"${{env.NEW_VERSION}}\"/" pyproject.toml

      - name: Commit version bump
        id: commit
        uses: EndBug/add-and-commit@v9
        with:
          add: "pyproject.toml"
          author_name: Seth Hinz
          author_email: sethhinz@me.com
          message: "Automatic version bump"
          tag: "v${{env.NEW_VERSION}}"
  build-macos:
    runs-on: macos-latest
    needs: bump
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.bump.outputs.commit }}
        
      - name: Extract current version
        run: echo "VERSION=$(sed -nr 's/version = "(.+)"/\1/p' pyproject.toml)" >> $GITHUB_ENV

      - name: Set up rye
        uses: sksat/setup-rye@v0.25.0

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: rye sync

      - name: Build
        run: |
          yes | rye run build
          zip flump-arm-macos.zip -r flump

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: "v${{ env.VERSION }}"
        run: |
          gh release create "$tag" \
            --title="Flump version ${{ env.VERSION }}" \
            --generate-notes \
            flump-arm-macos.zip
  build-windows:
    runs-on: windows-latest
    needs: [bump, build-macos]
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.bump.outputs.commit }}
        
      - name: Extract current version
        shell: pwsh
        run: |
          $version = Select-String -Path pyproject.toml -Pattern 'version = "(.+)"' | ForEach-Object { $_.Matches.Groups[1].Value }
          echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Build
        shell: pwsh
        run: |
          python -m venv .venv
          .\.venv\Scripts\activate.ps1
          pip install --editable .
          python -m src.flump.build
          Compress-Archive -Path flump -DestinationPath flump-windows.zip
      
      - name: Upload release asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload "v${{ env.VERSION }}" flump-windows.zip
